apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: almathex/database
          ports:
          - name: mysql-port
            containerPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  labels:
    app: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: almathex/service1
          ports:
          - name: service1-port
            containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels:
    app: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: almathex/service2
          ports:
          - name: service2-port
            containerPort: 5001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  labels:
    app: service3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
        - name: service3
          image: almathex/service3
          ports:
          - name: service3-port
            containerPort: 5002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4
  labels:
    app: service4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service4
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
        - name: service4
          image: almathex/service4
          ports:
          - name: service4-port
            containerPort: 5003

---

apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: app1

---

apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports: 
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  selector:
    app: service3
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: service4
spec:
  selector:
    app: service4
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP

---
